# -*- coding: utf-8 -*-
"""Shopify Stock Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaX8X0LUmnpPJpynAdtW46lJ4FpTYHSO
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/shopify_stock.csv')

df.head(5)

df.columns

df.dtypes

df["date"] = pd.to_datetime(df["date"],utc=True)
df['date'].dtype

df = df.sort_values("date")

plt.figure(figsize=(16, 8))

plt.plot(df.index, df["open"], label="open")
plt.plot(df.index, df["high"], label="high")
plt.plot(df.index, df["low"], label="low")
plt.plot(df.index, df["close"], label="close")

plt.title("Shopify Stock OHLC Prices")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x='date', y='close', data=df)
plt.title("Shopify's Closing Price Over Time")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.show()

df['daily_returns'] = df['close'].pct_change()

plt.figure(figsize=(15, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['daily_returns'].dropna(), bins=50, kde=True)
plt.title('Histogram of Daily Returns')
plt.xlabel('Daily Return')
plt.ylabel('Frequency')
plt.show()

sns.kdeplot(df['daily_returns'].dropna(), fill=True)
plt.title('KDE Plot of Daily Returns')
plt.xlabel('Daily Return')
plt.ylabel('Density')
plt.show()

df["Rolling_Volatility_20"] = (df["daily_returns"].rolling(window=20).std())

plt.figure(figsize=(12, 6))

plt.plot(df.index,df["Rolling_Volatility_20"])

plt.title("Shopify 20-Day Rolling Volatility")
plt.xlabel("Date")
plt.ylabel("Volatility")
plt.xticks(rotation=45)
plt.show()