# -*- coding: utf-8 -*-
"""Week 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFKmqEUSCCADSm6Q3HFJThjCMsw4UALx
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/drive/MyDrive/healthcare_dataset (1).csv")
df

df.head()

df.shape

df.info()

df.columns

df.describe()

df.isnull().sum()

df["Date of Admission"]=pd.to_datetime(df["Date of Admission"])
df["Discharge Date"]=pd.to_datetime(df["Discharge Date"])

df["Date of Admission"]

df["Discharge Date"]

stay_days=df["Discharge Date"]-df["Date of Admission"]
stay_days

billing=df.groupby(["Medical Condition","Insurance Provider",])["Billing Amount"].sum().unstack()
billing

billing.plot(kind="bar",stacked=True,figsize=(10,6))
plt.title("Billing Amount by Medical Condition and Insurance Provider")
plt.xlabel("Medical Condition")
plt.ylabel("Total Billing Amount")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,6))
sns.violinplot(x="Medical Condition",y="Billing Amount",data=df)
plt.title("Distribution of Billing Amount by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.xticks(rotation=45)
plt.show()

df['Admission Month']=df['Date of Admission'].dt.month
df['Admission Month']

monthly_admission=df.groupby('Admission Month').size()
monthly_admission

plt.figure(figsize=(12,6))
monthly_admission.plot(kind='line',marker="o")
plt.title("Monthly patient Admissions")
plt.xlabel("Month")
plt.ylabel("Number of Admissions")
plt.xticks(rotation=45)
plt.grid()
plt.show()

df['Stay Days'] = stay_days.dt.days
correlation_matrix=df[['Age', 'Stay Days', 'Billing Amount']].corr()
correlation_matrix

sns.heatmap(correlation_matrix,annot=True,cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

"""Executive Summary

> The analysis focuses on monthly patient admissions and relationships among healthcare variables. The line chart visualizes the number of patient admissions across different months, helping identify admission trends, fluctuations, and peak periods. The correlation heatmap examines the relationships between numerical healthcare variables, showing the strength and direction of their associations. Together, these visualizations provide a concise overview of patient admission patterns and important variable relationships, supporting data-driven healthcare monitoring and decision-making.
"""